#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cherrypy
Version  : 18.6.1
Release  : 36
URL      : https://files.pythonhosted.org/packages/c6/0d/f6acfd12f098b9f05b9146b79b5a3fad02f4047a7831b5f5c9ee3fe54d56/CherryPy-18.6.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c6/0d/f6acfd12f098b9f05b9146b79b5a3fad02f4047a7831b5f5c9ee3fe54d56/CherryPy-18.6.1.tar.gz
Summary  : Object-Oriented HTTP framework
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-cherrypy-bin = %{version}-%{release}
Requires: pypi-cherrypy-license = %{version}-%{release}
Requires: pypi-cherrypy-python = %{version}-%{release}
Requires: pypi-cherrypy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cheroot)
BuildRequires : pypi(jaraco.collections)
BuildRequires : pypi(more_itertools)
BuildRequires : pypi(portend)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(zc.lockfile)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
.. image:: https://img.shields.io/pypi/v/cherrypy.svg
:target: https://pypi.org/project/cherrypy

%package bin
Summary: bin components for the pypi-cherrypy package.
Group: Binaries
Requires: pypi-cherrypy-license = %{version}-%{release}

%description bin
bin components for the pypi-cherrypy package.


%package license
Summary: license components for the pypi-cherrypy package.
Group: Default

%description license
license components for the pypi-cherrypy package.


%package python
Summary: python components for the pypi-cherrypy package.
Group: Default
Requires: pypi-cherrypy-python3 = %{version}-%{release}

%description python
python components for the pypi-cherrypy package.


%package python3
Summary: python3 components for the pypi-cherrypy package.
Group: Default
Requires: python3-core
Provides: pypi(cherrypy)
Requires: pypi(cheroot)
Requires: pypi(jaraco.collections)
Requires: pypi(more_itertools)
Requires: pypi(portend)
Requires: pypi(zc.lockfile)

%description python3
python3 components for the pypi-cherrypy package.


%prep
%setup -q -n CherryPy-18.6.1
cd %{_builddir}/CherryPy-18.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649698784
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cherrypy
cp %{_builddir}/CherryPy-18.6.1/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-cherrypy/1c32898f7d523268279046931009a11aa4ad95b6
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cherryd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cherrypy/1c32898f7d523268279046931009a11aa4ad95b6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
